travis:
  secure:
    BINSTAR_TOKEN: WQlax1ibwRNITfgddXoyobBaSSLO0tlMie43rEpOWGCJcLPlDIpG+5p6XE7aqBGHqOOdqjvSD4ddmpixV6mDDVVodV37xSewSSPaBYjxSyRAZBjffVO3z/5Bum24fFz5H+xLxb3mmnmUgUbMYYpeH1LHhffba6dugSJ5nqItQAk1JQitMhEsDq+a/zWyMgc/w59Lq3520oN04iS8EuXbYt2ppcv0yCqrFSeRohNq5DYMeOB3qu/WYyE+gzz/Uj3IuVlg1jd+0TCoopnFZux8SPuAawbgVNPhGk+MPyLAGiRWzsLxD1ub6sIne+s0unQaOy2beDDZ9dgyvd6ktTA/wt15zpFeusVpyc0dm2qnTjKU+dg7RS7ApTXwNpkSJfhL9TV8q2HAGUoOk77esV708yL0EQHwrQ1x7PW61DZVkW6qjjqXSdm1o6970Oa3d9PVeVQb8F/CN/xgIid9xepW+zxs44T3z2KYrihfAyGZTwyqTug+jsQuNv9RZqaNc955r28KofOgJcA5vdIq5XsWDayt15Xzcgi39xEN6dbpjKWr1E/zYRYMyMq//5YR5+kkj++FhX4VBUm7nBtSAKsrqUUMaBM1WIE9lluIMenImjByHkQHY3nC3FzCSpnmg+yXt1EwBBF+/3AI9g2D3oZDaJZrxMIGTXXvynDY32HvFOc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
